version: "3.6"
services:
  ui-unit-tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit-tests
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./tests/entrypoint-unit.sh
  ui-integration-tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.7.0
    depends_on:
      - admin-ui
      - consumer-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./tests/entrypoint-cypress.sh integration
  e2e-tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.7.0
    depends_on:
      - admin-ui
      - consumer-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./tests/entrypoint-cypress.sh e2e
