stages:
- build
- test

build-services:
  stage: build
  image: shopozor/devspace
  services:
  - docker:dind
  # TODO: this is only for feature branches! for staging, we want the staging profile and we want to push the images
  script:
  - devspace build --build-sequential --skip-push -p feature-tests

build-test-images:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -f Dockerfile -t $CI_REGISTRY/shopozor/node-unit-tests:$CI_COMMIT_SHORT_SHA --target node-dependencies .
  - docker push $CI_REGISTRY/shopozor/node-unit-tests:$CI_COMMIT_SHORT_SHA

unit-test:
  stage: test
  image: $CI_REGISTRY/shopozor/node-unit-tests:$CI_COMMIT_SHORT_SHA
  script:
  - yarn test:unit:ci
  artifacts:
    reports:
      junit:
      - /app/frontend/admin-ui/test-reports/*.xml
      - /app/frontend/consumer-ui/test-reports/*.xml