stages:
- lint
- prepare-fixtures
- test
- build
- deploy
- validate

.log_into_docker: &log_into_docker
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

generate-fixtures:
  variables:
    IMAGE_NAME: fixtures-generator
    CONTAINER_NAME: fixtures-generator
  stage: prepare-fixtures
  image: docker:latest
  script:
  - docker build -f Dockerfile -t $IMAGE_NAME --target fixtures-app-ci .
  - docker run --name $CONTAINER_NAME --env PYTHONDONTWRITEBYTECODE=1 $IMAGE_NAME
  - docker cp $CONTAINER_NAME:/app/fixtures ./shared/
  artifacts:
    paths:
    - $CI_PROJECT_DIR/shared/fixtures/
  after_script:
  - docker container rm $CONTAINER_NAME

hasura-service-tests:
  stage: test
  image: shopozor/docker-compose:latest
  before_script:
  - docker-compose build database-service-tests service-integration-tests
  script:
  - docker-compose up --exit-code-from database-service-tests database-service-tests
  - docker-compose up --exit-code-from service-integration-tests service-integration-tests
  after_script:
  - docker cp services_database-service-tests_1:/app/backend/database-service/test-reports ./backend/database-service/test-reports
  - docker cp services_service-integration-tests_1:/app/backend/tests/test-reports ./backend/tests/test-reports
  - docker-compose down --remove-orphans
  artifacts:
    reports:
      junit:
      - $CI_PROJECT_DIR/backend/database-service/test-reports/*.xml
      - $CI_PROJECT_DIR/backend/tests/test-reports/*.xml

node-unit-tests:
  stage: test
  image: node:13.8.0-alpine
  script:
  - yarn && yarn bootstrap
  - yarn test:unit:ci
  artifacts:
    reports:
      junit:
      # wildcard path "**" does not work: https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      - $CI_PROJECT_DIR/frontend/*/test-reports/*.xml
      - $CI_PROJECT_DIR/backend/*/test-reports/*.xml

build-services:
  stage: build
  image: shopozor/devspace
  script:
  - devspace build --build-sequential --skip-push -p feature-tests
  except:
  - master
  - pre-production
  - production

pages:
  image: shopozor/pickles
  script:
  - APP=admin-ui mono /pickles/Pickles.exe --feature-directory=./frontend/$APP/cypress/e2e --output-directory=public/$APP --system-under-test-name=$APP --system-under-test-version=${CI_COMMIT_SHORT_SHA} --language=fr --documentation-format=dhtml --exp --et 'in-preparation'
  - APP=consumer-ui mono /pickles/Pickles.exe --feature-directory=./frontend/$APP/cypress/e2e --output-directory=public/$APP --system-under-test-name=$APP --system-under-test-version=${CI_COMMIT_SHORT_SHA} --language=fr --documentation-format=dhtml --exp --et 'in-preparation'
  artifacts:
    paths:
    - public
  only:
  - master