# TODO: lint!

stages:
- build
- test

generate-fixtures:
  variables:
    IMAGE_NAME: fixtures-generator
    CONTAINER_NAME: fixtures-generator
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker build -f Dockerfile -t $IMAGE_NAME --target fixtures-app .
  - docker run --name $CONTAINER_NAME --env PYTHONDONTWRITEBYTECODE=1 $IMAGE_NAME
  - docker cp $CONTAINER_NAME:/app/fixtures ./shared/
  artifacts:
    paths:
    - $CI_PROJECT_DIR/shared/fixtures/
  after_script:
  - docker container rm $CONTAINER_NAME

build-services:
  stage: build
  image: shopozor/devspace
  services:
  - docker:dind
  # TODO: this is only for feature branches! for staging, we want the staging profile and we want to push the images
  script:
  - devspace build --build-sequential --skip-push -p feature-tests

node-unit-tests:
  stage: test
  image: node:13.8.0-alpine
  script:
  - yarn && yarn bootstrap
  - yarn test:unit:ci
  artifacts:
    reports:
      junit:
      # wildcard path "**" does not work: https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      - $CI_PROJECT_DIR/frontend/*/test-reports/*.xml
      - $CI_PROJECT_DIR/backend/*/test-reports/*.xml

# TODO: hasura unit tests!