stages:
- lint
- fixtures-generation
- unit-test
- build
- deploy
- env-test

variables:
  HASURA_TESTS_IMAGE: $CI_REGISTRY/shopozor/hasura-test

.log_into_docker: &log_into_docker
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

generate-fixtures:
  variables:
    IMAGE_NAME: fixtures-generator
    CONTAINER_NAME: fixtures-generator
  stage: fixtures-generation
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker build -f Dockerfile -t $IMAGE_NAME --target fixtures-app .
  - docker run --name $CONTAINER_NAME --env PYTHONDONTWRITEBYTECODE=1 $IMAGE_NAME
  - docker cp $CONTAINER_NAME:/app/fixtures ./shared/
  artifacts:
    paths:
    - $CI_PROJECT_DIR/shared/fixtures/
  after_script:
  - docker container rm $CONTAINER_NAME

build-tests:
  before_script:
  - *log_into_docker
  stage: unit-test
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker build -f Dockerfile-dev -t $HASURA_TESTS_IMAGE --target hasura-test-ci .
  - docker push $HASURA_TESTS_IMAGE

# TODO: this belongs to deployment phase and needs to call deploy, not build!
# TODO: in a feature branch, I'd like to just build the images, just to see that it is working
build-services:
  stage: build
  image: shopozor/devspace
  services:
  - docker:dind
  # TODO: this is only for feature branches! for staging, we want the staging profile and we want to push the images
  script:
  - devspace build --build-sequential --skip-push -p feature-tests

node-unit-tests:
  stage: unit-test
  image: node:13.8.0-alpine
  script:
  - yarn && yarn bootstrap
  - yarn test:unit:ci
  artifacts:
    reports:
      junit:
      # wildcard path "**" does not work: https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      - $CI_PROJECT_DIR/frontend/*/test-reports/*.xml
      - $CI_PROJECT_DIR/backend/*/test-reports/*.xml

# TODO: probably deploy this on the k8s cluster, in a random test namespace!
# TODO: we should refactor the test code so that it can be run on the repo directly
hasura-unit-tests:
  stage: unit-test
  image: $HASURA_TESTS_IMAGE
  variables:
    HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
    HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  services:
  - name: postgres:11.2-alpine
    alias: postgres
  - name: hasura/graphql-engine:v1.0.0
    alias: graphql-engine
  script:
  - wait-for-it graphql-engine:8080 -t 60 -s -- echo "OK"
