stages:
- lint
- fixtures-generation
- unit-test
- build
- deploy
- env-test

.log_into_docker: &log_into_docker
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# TODO: fix this so that it uses the code of the current git, as we do for the tests!
generate-fixtures:
  variables:
    IMAGE_NAME: fixtures-generator
    CONTAINER_NAME: fixtures-generator
  stage: fixtures-generation
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker build -f Dockerfile -t $IMAGE_NAME --target fixtures-app .
  - docker run --name $CONTAINER_NAME --env PYTHONDONTWRITEBYTECODE=1 $IMAGE_NAME
  - docker cp $CONTAINER_NAME:/app/fixtures ./shared/
  artifacts:
    paths:
    - $CI_PROJECT_DIR/shared/fixtures/
  after_script:
  - docker container rm $CONTAINER_NAME

hasura-service-tests:
  stage: unit-test
  image: shopozor/docker-compose:latest
  services:
  - docker:dind
  script:
  - docker-compose build database-service-tests
  - docker-compose up database-service-tests
  - ls backend/database-service
  artifacts:
    reports:
      junit:
      - $CI_PROJECT_DIR/backend/database-service/test-reports/*.xml

node-unit-tests:
  stage: unit-test
  image: node:13.8.0-alpine
  script:
  - yarn && yarn bootstrap
  - yarn test:unit:ci
  artifacts:
    reports:
      junit:
      # wildcard path "**" does not work: https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      - $CI_PROJECT_DIR/frontend/*/test-reports/*.xml
      - $CI_PROJECT_DIR/backend/*/test-reports/*.xml

# TODO: this belongs to deployment phase and needs to call deploy, not build!
# TODO: in a feature branch, I'd like to just build the images, just to see that it is working
build-services:
  stage: build
  image: shopozor/devspace
  services:
  - docker:dind
  # TODO: this is only for feature branches! for staging, we want the staging profile and we want to push the images
  script:
  - devspace build --build-sequential --skip-push -p feature-tests