- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.4
  hooks:
  - id: autopep8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=feature]
    exclude: __snapshots__/*
  - id: check-json
    exclude: .vscode/*
  - id: pretty-format-json
    exclude: .vscode/*
    args: [--autofix, --indent=2]
# - repo: local
#   hooks:
#     - id: eslint
#       name: eslint
#       entry: yarn lint
#       language: system
#       pass_filenames: false