- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.4
  hooks:
  - id: autopep8
- repo: https://github.com/shopozor/pre-commit-hooks
  rev: ab46cd3bffd7c1c17f433eb23682fba6f8cb4a51
  hooks:
    - id: check-feature-tags
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=feature]
  - id: check-json
    exclude: .vscode/*
  - id: pretty-format-json
    exclude: .vscode/*
    args: [--autofix, --indent=2]
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v6.7.0
  hooks:
  - id: eslint
    args: [--fix]
    exclude: \..*\.js
    additional_dependencies:
    - babel-eslint@10.0.1
    - eslint@6.7.0
    - eslint-config-standard@14.1.0
    - eslint-friendly-formatter@4.0.1
    - eslint-loader@3.0.2
    - eslint-plugin-chai-friendly@0.5.0
    - eslint-plugin-cucumber@1.4.0
    - eslint-plugin-cypress@2.6.1
    - eslint-plugin-import@2.18.2
    - eslint-plugin-node@10.0.0
    - eslint-plugin-promise@4.2.1
    - eslint-plugin-standard@4.0.1
    - eslint-plugin-vue@6.0.1