- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.4
  hooks:
  - id: autopep8
- repo: https://github.com/shopozor/pre-commit-hooks
  rev: ab46cd3bffd7c1c17f433eb23682fba6f8cb4a51
  hooks:
    - id: check-feature-tags
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=feature]
    exclude: __snapshots__/*
  - id: check-json
    exclude: .vscode/*
  - id: pretty-format-json
    exclude: .vscode/*
    args: [--autofix, --indent=2]
- repo: local
  hooks:
    - id: eslint
      name: eslint
      entry: yarn lint
      language: system
      pass_filenames: false
    - id: test-all
      name: test-all
      entry: make dev-test.all
      language: system
      pass_filenames: false
      stages: [push]