version: "3.6"
services:
  jest-unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: jest-unit-testing
    image: ${PRODUCT:-shopozor}/jest-unit-testing:${TAG:-local}
    restart: "no"
    volumes:
      - ./frontend/consumer-ui/test-reports:/app/frontend/consumer-ui/test-reports
      - ./frontend/admin-ui/test-reports:/app/frontend/admin-ui/test-reports
      - ./backend/site-generator-service/test-reports:/app/backend/site-generator-service/test-reports