version: "3.6"
services:
  hasura-service-tests:
    build:
      context: ./database-service
      dockerfile: ./Dockerfile
      target: integration-test
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./database-service:/app
      - ./fixtures:/app/fixtures
      - ./graphql:/app/fixtures/graphql/calls
      - ./test-utils:/app/tests/utils
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=./tests:$PYTHONPATH
    entrypoint: ./tests/entrypoint.sh
  fixtures-service:
    build:
      context: .
      dockerfile: ./fixtures-generator/Dockerfile
      target: builder
    user: ${USER_ID}
    volumes:
      - ./fixtures-generator:/app
      - ./test-utils:/app/test_utils
  features-tests:
    build:
      context: ./features
      dockerfile: ./Dockerfile
      target: features-tests
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./database-service:/db
      - ./features:/app
      - ./fixtures:/app/fixtures
      - ./test-utils:/app/test_utils
    entrypoint: behave --junit --junit-directory ${TEST_REPORTS_FOLDER:-test-reports} --tags ~wip

volumes:
  db_data:

networks:
  default:
    name: default-network
