version: "3.6"
services:
  admin-ui:
    image: ${PRODUCT:-shopozor}/admin-ui:${TAG:-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: admin-ui
      args:
        GRAPHQL_API: http://graphql-engine:8080/v1/graphql/
    volumes:
      - ./frontend/admin-ui/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/admin-ui/dist/spa:/srv
    ports:
      - ${ADMIN_UI_PORT:-4000}:80
    depends_on:
      - graphql-engine
    restart: "no"
  consumer-ui:
    image: nginx:1.16.0
    working_dir: /srv/static
    volumes:
      - ./frontend/consumer-ui/conf/nginx.conf:/etc/nginx/nginx.conf
      - static_site_data:/srv
    depends_on:
      - minio
    ports:
      - ${CONSUMER_UI_PORT:-3000}:80
    restart: "no"

