version: "3.6"
services:
  ui-unit-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: unit-tests
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-unit.sh
  admin-storybook:
    image: abiosoft/caddy:latest
    volumes:
      - ./frontend/Caddyfile:/etc/Caddyfile
      - ./frontend/admin-ui/storybook-static:/srv
    ports:
      - ${ADMIN_STORYBOOK_PORT:-7006}:8080
    restart: "no"
  consumer-storybook:
    image: abiosoft/caddy:latest
    volumes:
      - ./frontend/Caddyfile:/etc/Caddyfile
      - ./frontend/consumer-ui/storybook-static:/srv
    ports:
      - ${CONSUMER_STORYBOOK_PORT:-6006}:8080
    restart: "no"
  ui-integration-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.8.0
    depends_on:
      - admin-storybook
      - consumer-storybook
    user: root
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-cypress.sh integration
  e2e-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.8.0
    depends_on:
      - admin-ui
      - consumer-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-cypress.sh e2e
