version: "3.6"
services:
  ui:
    build:
      context: admin-ui
      dockerfile: ./Dockerfile
      target: app
      args:
        GRAPHQL_API: http://graphql-engine:${API_PORT:-8080}/v1/graphql/
    ports:
      - ${UI_PORT:-4000}:4000
    depends_on:
      - graphql-engine
    restart: "no"
    entrypoint: yarn start
