version: "3.6"
services:
  postgres:
    image: postgres:11.2-alpine
    restart: "no"
    volumes:
      - db_data:/var/lib/postgresql-11.2/data
  graphql-engine:
    build:
      context: ./database-service
      dockerfile: ./Dockerfile
      target: app
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - postgres
    restart: "no"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  fixtures-service:
    build:
      context: .
      dockerfile: ./fixtures-generator/Dockerfile
      target: app
    restart: "no"
    volumes:
      - ./fixtures:/app/fixtures
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint: ./entrypoint.sh

volumes:
  db_data:

networks:
  default:
    name: default-network
