version: "3.6"
services:
  database-service-tests:
    build:
      context: backend/database-service
      dockerfile: Dockerfile
      target: test
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./backend/database-service:/app
      - ./backend/test-utils:/app/utils
      - ./shared/fixtures:/app/fixtures
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=./tests:$PYTHONPATH
    entrypoint: ./tests/entrypoint.sh
  service-integration-tests:
    build:
      context: backend
      dockerfile: tests/Dockerfile
      target: integration-test
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./backend/tests:/app
      - ./backend/test-utils:/app/utils
      - ./shared/fixtures:/app/fixtures
      - ./shared/graphql:/app/fixtures/graphql/calls
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=./tests:$PYTHONPATH
    entrypoint: ./entrypoint.sh
  fixtures-service:
    build:
      context: backend
      dockerfile: fixtures-generator/Dockerfile
      target: builder
    volumes:
      - ./backend/fixtures-generator:/app
      - ./backend/test-utils:/app/test_utils
  features-tests:
    build:
      context: backend/features
      dockerfile: Dockerfile
      target: features-tests
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./backend/database-service:/db
      - ./backend/features:/app
      - ./shared/fixtures:/app/fixtures
      - ./backend/test-utils:/app/test_utils
    entrypoint: ./entrypoint.sh test-reports

volumes:
  db_data:
