version: "3.6"
services:
  hasura-service-tests:
    build:
      context: ./backend/database-service
      dockerfile: ./Dockerfile
      target: integration-test
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./backend/database-service:/app
      - ./shared/fixtures:/app/fixtures
      - ./shared/graphql:/app/fixtures/graphql/calls
      - ./backend/test-utils:/app/tests/utils
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=./tests:$PYTHONPATH
    entrypoint: ./tests/entrypoint.sh
  fixtures-service:
    build:
      context: .
      dockerfile: ./backend/fixtures-generator/Dockerfile
      target: builder
    volumes:
      - ./backend/fixtures-generator:/app
      - ./backend/test-utils:/app/test_utils
  features-tests:
    build:
      context: ./backend/features
      dockerfile: ./Dockerfile
      target: features-tests
    restart: "no"
    depends_on:
      - graphql-engine
    volumes:
      - ./backend/database-service:/db
      - ./backend/features:/app
      - ./shared/fixtures:/app/fixtures
      - ./backend/test-utils:/app/test_utils
    entrypoint: behave --junit --junit-directory ${TEST_REPORTS_FOLDER:-test-reports} --tags ~wip

volumes:
  db_data:
