version: "3.6"
services:
  admin-storybook:
    image: ${PRODUCT:-shopozor}/admin-storybook:${TAG:-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: admin-storybook
    volumes:
      - ./frontend/admin-ui/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${ADMIN_STORYBOOK_PORT:-7006}:80
    restart: "no"
  consumer-storybook:
    image: ${PRODUCT:-shopozor}/consumer-storybook:${TAG:-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer-storybook
    volumes:
      - ./frontend/consumer-ui/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${CONSUMER_STORYBOOK_PORT:-6006}:80
    restart: "no"
  ui-integration-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.8.0
    depends_on:
      - admin-storybook
      - consumer-storybook
    user: root
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-cypress.sh integration
  e2e-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.8.0
    depends_on:
      - admin-ui
      - consumer-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-cypress.sh e2e
