version: "3.6"
services:
  ui-unit-tests:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: unit-tests
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-unit.sh
  ui-integration-tests:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: cypress-tests
    user: ${USER_ID}
    environment:
      CYPRESS_baseUrl: http://admin-ui:${UI_PORT:-4000}/#
    depends_on:
      - admin-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-integration.sh
  e2e-tests:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: cypress-tests
    user: ${USER_ID}
    environment:
      CYPRESS_baseUrl: http://admin-ui:${UI_PORT:-4000}/#
    depends_on:
      - admin-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-e2e.sh
