version: "3.6"
services:
  admin-ui:
    build:
      context: .
      dockerfile: ./frontend/admin-ui/Dockerfile
      target: app
      args:
        GRAPHQL_API: http://graphql-engine:${API_PORT:-8080}/v1/graphql/
    ports:
      - ${UI_PORT:-4000}:4000
    depends_on:
      - graphql-engine
    restart: "no"
    entrypoint: yarn start
