version: "3.6"
services:
  admin-ui:
    image: abiosoft/caddy:latest
    volumes:
      - ./frontend/Caddyfile:/etc/Caddyfile
      - ./frontend/admin-ui/dist/spa:/srv
    ports:
      - ${ADMIN_UI_PORT:-4000}:8080
    depends_on:
      - graphql-engine
    restart: "no"
  consumer-ui:
    image: abiosoft/caddy:latest
    volumes:
      - ./frontend/Caddyfile:/etc/Caddyfile
      - ./frontend/consumer-ui/dist:/srv
    depends_on:
      - minio
    ports:
      - ${CONSUMER_UI_PORT:-3000}:8080
    restart: "no"