version: "3.6"
services:
  ui-unit-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: unit-tests
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-unit.sh
  admin-storybook:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: storybook
    environment:
      ADMIN_STORYBOOK_HOST: "0.0.0.0"
      ADMIN_STORYBOOK_PORT: 4000
    ports:
      - ${ADMIN_STORYBOOK_PORT:-7006}:4000
    restart: "no"
    entrypoint: lerna run storybook:ci --scope admin-ui
  consumer-storybook:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: storybook
    environment:
      CONSUMER_STORYBOOK_HOST: "0.0.0.0"
      CONSUMER_STORYBOOK_PORT: 4000
    ports:
      - ${CONSUMER_STORYBOOK_PORT:-6006}:4000
    restart: "no"
    entrypoint: lerna run storybook:ci --scope consumer-ui
  ui-integration-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.8.0
    depends_on:
      - admin-storybook
      - consumer-storybook
    user: root
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-cypress.sh integration
  e2e-tests:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: cypress-tests
      args:
        CYPRESS_VERSION: 3.8.0
    depends_on:
      - admin-ui
      - consumer-ui
    restart: "no"
    volumes:
      - .:/app
    entrypoint: ./frontend/tests/entrypoint-cypress.sh e2e
