version: "3.6"
services:
  admin-ui:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: app
      args:
        GRAPHQL_API: http://graphql-engine:${API_PORT:-8080}/v1/graphql/
    ports:
      - ${ADMIN_UI_PORT:-4000}:4000
    depends_on:
      - graphql-engine
    restart: "no"
    entrypoint: lerna run start --scope admin-ui
  consumer-ui:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: app
      args:
        GRAPHQL_API: http://graphql-engine:${API_PORT:-8080}/v1/graphql/
    environment:
      NUXT_PORT: 4000
      NUXT_HOST: "0.0.0.0"
    ports:
      - ${CONSUMER_UI_PORT:-3000}:4000
    depends_on:
      - graphql-engine
    restart: "no"
    entrypoint: lerna run start --scope consumer-ui