apiVersion: skaffold/v2alpha2
kind: Config

build:
  artifacts:
    - image: shopozor/assets-fixtures
      context: .
      docker:
        dockerfile: ./backend/assets-service/Dockerfile
  local:
    push: false

deploy:
  helm:
    releases:
      - name: minio
        chartPath: bitnami/minio
        remote: true
        namespace: dev
        values:
        overrides:
          fullnameOverride: minio
          mode: standalone
          clusterDomain: cluster.local
          persistence:
            enabled: false
            size: 10Gi
          disableWebUI: false
          service:
            type: NodePort
    flags:
      upgrade:
        - --install
  kubectl:
    manifests:
      - backend/assets-service/k8s/setup/*
      - backend/assets-service/k8s/testing/*
    flags:
      global:
        - --namespace=dev

profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: minio
            chartPath: bitnami/minio
            remote: true
            namespace: staging
            values:
            overrides:
              fullnameOverride: minio
              mode: distributed
              persistence:
                enabled: true
                storageClass: jelastic-dynamic-volume
                size: 10Gi
              disableWebUI: false
        flags:
          upgrade:
            - --install
      kubectl:
        manifests:
          - backend/assets-service/k8s/setup/*
          - backend/assets-service/k8s/testing/*
        flags:
          global:
            - --namespace=staging
  - name: production
    deploy:
      helm:
        releases:
          - name: minio
            chartPath: bitnami/minio
            remote: true
            namespace: production
            values:
            overrides:
              fullnameOverride: minio
              mode: distributed
              persistence:
                enabled: true
                storageClass: jelastic-dynamic-volume
                size: 10Gi
              disableWebUI: true
        flags:
          upgrade:
            - --install
      kubectl:
        manifests:
          - backend/assets-service/k8s/setup/*
        flags:
          global:
            - --namespace=production