apiVersion: skaffold/v2alpha2
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: shopozor/assets-fixtures
      context: .
      docker:
        dockerfile: backend/assets-service/Dockerfile
    - image: shopozor/graphql-engine
      context: backend/database-service
      docker:
        dockerfile: Dockerfile
        target: hasura-migrations
    - image: shopozor/fixtures-service
      context: .
      docker:
        dockerfile: backend/fixtures-generator/Dockerfile
        target: app
    - image: shopozor/site-generator-service
      context: .
      docker:
        dockerfile: Dockerfile
        target: site-generator
        buildArgs:
          GRAPHQL_API: http://hasura:8080/v1/graphql/
    - image: shopozor/admin-ui
      context: .
      docker:
        dockerfile: Dockerfile
        target: admin-ui
        buildArgs:
          GRAPHQL_API: http://hasura:8080/v1/graphql/
    # TODO: here we are still missing the consumer-ui!
    - image: shopozor/admin-storybook
      context: .
      docker:
        dockerfile: Dockerfile
        target: admin-storybook
        buildArgs:
          GRAPHQL_API: http://hasura:8080/v1/graphql/
    - image: shopozor/consumer-storybook
      context: .
      docker:
        dockerfile: Dockerfile
        target: consumer-storybook
        buildArgs:
          GRAPHQL_API: http://hasura:8080/v1/graphql/

deploy:
  helm:
    releases:
      - name: minio
        chartPath: bitnami/minio
        remote: true
        namespace: dev
        overrides:
          # TODO: this override is probably not necessary
          fullnameOverride: minio
          mode: standalone
          clusterDomain: cluster.local
          persistence:
            enabled: false
            size: 10Gi
          disableWebUI: false
          accessKey:
            password: minio
          secretKey:
            password: minio123
      # TODO: we need to decide if the assets are pushed by default to the assets service
      #       or if we proceed as with the database fixtures!
      - name: minio-initialization
        chartPath: backend/assets-service/chart
        namespace: dev
        values:
          image: shopozor/assets-fixtures
        overrides:
          fixtures:
            enabled: true
          minio:
            fullname: minio
            client:
              alias: minio
            server:
              port: 9000
      - name: postgres
        chartPath: bitnami/postgresql-ha
        remote: true
        namespace: dev
        overrides:
          # TODO: this override is probably not necessary
          fullnameOverride: postgres
          postgresql:
            username: postgres
            database: postgres
          persistence:
            mountPath: /opt/bitnami/postgresql/data
          volumePermissions:
            enabled: true
      - name: hasura
        chartPath: backend/database-service/chart
        namespace: dev
        values:
          image: shopozor/graphql-engine
        overrides:
          # TODO: this override is probably not necessary
          nameOverride: hasura
          postgres:
            secretName: postgres-postgresql
            username: postgres
            database: postgres
            hostname: postgres-pgpool.dev
          hasura:
            server:
              port: 8080
      # TODO: this must not stay in the dev deployment; this is only for staging
      - name: database-fixtures
        chartPath: backend/fixtures-generator/chart
        namespace: dev
        values:
          image: shopozor/fixtures-service
        overrides:
          hasura:
            host: hasura
            port: 8080
      - name: site-generator-service
        chartPath: backend/site-generator-service/chart
        namespace: dev
        values:
          image: shopozor/site-generator-service
        overrides:
          services:
            assets:
              name: minio
              port: 9000
            hasura:
              name: hasura
              port: 8080
      - name: admin-ui
        chartPath: frontend/admin-ui/chart
        namespace: dev
        values:
          ui.image: shopozor/admin-ui
          storybook.image: shopozor/admin-storybook
        overrides:
          ui:
            ingress:
              enabled: false
          storybook:
            enabled: true
            ingress:
              enabled: false
          services:
            assets:
              name: minio
              port: 9000
    flags:
      upgrade:
        - --install

# TODO: put env vars in the section below that will then substituted with e.g. the jelastic environment name!
profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: minio
            chartPath: bitnami/minio
            remote: true
            namespace: staging
            values:
            overrides:
              fullnameOverride: minio
              mode: distributed
              persistence:
                enabled: true
                storageClass: jelastic-dynamic-volume
                size: 10Gi
              disableWebUI: false
        flags:
          upgrade:
            - --install
  - name: production
    deploy:
      helm:
        releases:
          # TODO: use https://github.com/bitnami/charts/blob/master/bitnami/minio/values-production.yaml
          - name: minio
            chartPath: bitnami/minio
            remote: true
            namespace: production
            values:
            overrides:
              fullnameOverride: minio
              mode: distributed
              persistence:
                enabled: true
                storageClass: jelastic-dynamic-volume
                size: 10Gi
              disableWebUI: true
        flags:
          upgrade:
            - --install