apiVersion: skaffold/v2alpha2
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: shopozor/assets-fixtures
      context: .
      docker:
        dockerfile: backend/assets-service/Dockerfile
    - image: shopozor/graphql-engine
      context: backend/database-service
      docker:
        dockerfile: Dockerfile
        target: hasura-migrations
    - image: shopozor/fixtures-service
      context: .
      docker:
        dockerfile: backend/fixtures-generator/Dockerfile
        target: app
    - image: shopozor/admin-ui
      context: .
      docker:
        dockerfile: Dockerfile
        target: admin-ui
        buildArgs:
          GRAPHQL_API: http://api.shopozor/v1/graphql/
          ASSETS_API: http://assets.shopozor/
    - image: shopozor/consumer-ui-spa
      context: .
      docker:
        dockerfile: Dockerfile
        target: consumer-ui-spa
        buildArgs:
          GRAPHQL_API: http://api.shopozor/v1/graphql/
          ASSETS_API: http://assets.shopozor/
    - image: shopozor/admin-storybook
      context: .
      docker:
        dockerfile: Dockerfile
        target: admin-storybook
        buildArgs:
          ASSETS_API: http://assets.shopozor/
    - image: shopozor/consumer-storybook
      context: .
      docker:
        dockerfile: Dockerfile
        target: consumer-storybook
        buildArgs:
          ASSETS_API: http://assets.shopozor/

deploy:
  helm:
    releases:
      - name: minio
        chartPath: bitnami/minio
        remote: true
        namespace: dev
        overrides:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
            - name: assets.shopozor
              path: /
          mode: standalone
          clusterDomain: localhost
          persistence:
            enabled: false
            size: 10Gi
          disableWebUI: false
          accessKey:
            password: minio
          secretKey:
            password: minio123
          service:
            port: 9000
      # TODO: we need to decide if the assets are pushed by default to the assets service
      #       or if we proceed as with the database fixtures!
      - name: minio-initialization
        chartPath: backend/assets-service/chart
        namespace: dev
        values:
          image: shopozor/assets-fixtures
        overrides:
          fixtures:
            enabled: true
          minio:
            fullname: minio
            client:
              alias: minio
            server:
              port: 9000
      - name: postgres
        chartPath: bitnami/postgresql-ha
        remote: true
        namespace: dev
        overrides:
          fullnameOverride: postgres
          postgresql:
            username: postgres
            database: postgres
          persistence:
            enabled: false
            # mountPath: /opt/bitnami/postgresql/data
          volumePermissions:
            enabled: true
      - name: api
        chartPath: backend/database-service/chart
        namespace: dev
        values:
          image: shopozor/graphql-engine
        overrides:
          ingress:
            enabled: true
            hosts:
            - host: api.shopozor
              paths:
                - /
          postgres:
            secretName: postgres-postgresql
            username: postgres
            database: postgres
            hostname: postgres-pgpool
          hasura:
            server:
              port: 8080
            cors:
              enabled: true
              domain: "*"
          service:
            port: 8080
      # TODO: this must not stay in the dev deployment; this is only for staging
      - name: database-fixtures
        chartPath: backend/fixtures-generator/chart
        namespace: dev
        values:
          image: shopozor/fixtures-service
        overrides:
          services:
            api:
              hostname: api
              port: 8080
      - name: admin-ui
        chartPath: frontend/admin-ui/chart
        namespace: dev
        values:
          ui.image: shopozor/admin-ui
          storybook.image: shopozor/admin-storybook
        overrides:
          ui:
            service:
              port: 4000
              type: ClusterIP
          storybook:
            enabled: true
            service:
              port: 7006
            ingress:
              enabled: false
          services:
            api:
              hostname: api
      - name: consumer-ui
        chartPath: frontend/consumer-ui/chart
        namespace: dev
        values:
          ui.image: shopozor/consumer-ui-spa
          storybook.image: shopozor/consumer-storybook
        overrides:
          ui:
            service:
              type: ClusterIP
              port: 3000
          storybook:
            enabled: true
            ingress:
              enabled: false
            service:
              port: 6006
          services:
            api:
              hostname: api
    flags:
      upgrade:
        - --install

# TODO: test this:
# portForward:
# - resourceType: service
#   resourceName: minio
#   namespace: dev
#   port: 9000
#   localPort: 9000
# - resourceType: service
#   resourceName: consumer-ui
#   namespace: dev
#   port: 80
#   localPort: 80
# - resourceType: service
#   resourceName: consumer-ui-storybook
#   namespace: dev
#   port: 80
#   localPort: 6006
# - resourceType: service
#   resourceName: admin-ui
#   namespace: dev
#   port: 80
#   localPort: 4000
# - resourceType: service
#   resourceName: admin-ui-storybook
#   namespace: dev
#   port: 80
#   localPort: 7006
# - resourceType: service
#   resourceName: hasura
#   namespace: dev
#   port: 8080
#   localPort: 8080
# # - resourceType: service
# #   resourceName: site-generator-service
# #   namespace: dev
# #   port: 8080
# #   localPort: 8081

# TODO: put env vars in the section below that will then substituted with e.g. the jelastic environment name!
profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: minio
            chartPath: bitnami/minio
            remote: true
            namespace: staging
            values:
            overrides:
              fullnameOverride: minio
              mode: distributed
              persistence:
                enabled: true
                storageClass: jelastic-dynamic-volume
                size: 10Gi
              disableWebUI: false
        # TODO: here we need to deploy an "empty" consumer-ui (with no knowledge of the database)
        flags:
          upgrade:
            - --install
  - name: production
    deploy:
      helm:
        releases:
          # TODO: use https://github.com/bitnami/charts/blob/master/bitnami/minio/values-production.yaml
          - name: minio
            chartPath: bitnami/minio
            remote: true
            namespace: production
            values:
            overrides:
              fullnameOverride: minio
              mode: distributed
              persistence:
                enabled: true
                storageClass: jelastic-dynamic-volume
                size: 10Gi
              disableWebUI: true
        flags:
          upgrade:
            - --install