{{- if and .Values.storybook.enabled .Values.storybook.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $svcPort := .Values.storybook.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-storybook
  labels:
{{ include "chart.labels" . | indent 4 }}
  {{- with .Values.storybook.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.storybook.ingress.tls }}
  tls:
  {{- range .Values.storybook.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  # TODO: store the ingress host in a secret or let the ci / cd substitute env vars in the skaffold config
  # https://github.com/bitnami-labs/sealed-secrets
  {{- range .Values.storybook.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-storybook
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
