kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}
data:
  # TODO: is there a way to prevent this copy/pasting?
  ui: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      proxy_cache_path  /data/nginx/cache levels=1:2 keys_zone=nuxt-cache:25m max_size=1g inactive=60m use_temp_path=off;

      map $sent_http_content_type $expires {
          "text/html"                 1h; # set this to your needs
          "text/html; charset=utf-8"  1h; # set this to your needs
          default                     7d; # set this to your needs
      }

      server {
          listen          80;             # the port nginx is listening on
          server_name     your-domain;    # setup your domain here

          gzip            on;
          gzip_types      text/plain application/xml text/css application/javascript;
          gzip_min_length 1000;

          charset utf-8;

          root /srv/static

          location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|otf|ttf|svg|js|css)$ {
              expires $expires;
              add_header Pragma public;
              add_header Cache-Control "public";

              try_files $uri $uri/ @proxy;
          }

          location / {
              expires $expires;
              add_header Content-Security-Policy "default-src 'self' 'unsafe-inline';";
              add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
              add_header X-Frame-Options "SAMEORIGIN";

              try_files $uri $uri/index.html @proxy; # for generate.subFolders: true
              # try_files $uri $uri.html @proxy; # for generate.subFolders: false
          }

          location @proxy {
              expires $expires;
              add_header Content-Security-Policy "default-src 'self' 'unsafe-inline';";
              add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
              add_header X-Frame-Options "SAMEORIGIN";
              add_header X-Cache-Status $upstream_cache_status;

              proxy_redirect                      off;
              proxy_set_header Host               $host;
              proxy_set_header X-Real-IP          $remote_addr;
              proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto  $scheme;
              proxy_ignore_headers        Cache-Control;
              proxy_http_version          1.1;
              proxy_read_timeout          1m;
              proxy_connect_timeout       1m;
              proxy_pass                  http://127.0.0.1:3000; # set the address of the Node.js instance here
              proxy_cache                 nuxt-cache;
              proxy_cache_bypass          $arg_nocache; # probably better to change this
              proxy_cache_valid           200 302  60m; # set this to your needs
              proxy_cache_valid           404      1m;  # set this to your needs
              proxy_cache_lock            on;
              proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
              proxy_cache_key             $uri$is_args$args;
              proxy_cache_purge           PURGE from 127.0.0.1;
          }
      }
  storybook: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      server {
        listen 8080;
        server_name localhost;

        root /srv;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        index index.html;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        access_log off;
        error_log  /var/log/nginx/app.log error;

        location ~ /\.(?!well-known).* {
            deny all;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
      }
    }