apiVersion: batch/v1
kind: Job
metadata:
  name: expose-assets-buckets
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      initContainers:
      - name: wait-for-minio
        image: bitnami/minio-client
        env:
          - name: MINIO_SERVER_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                # this is minio.fullname or fullnameOverride
                name: minio
                key: access-key
          - name: MINIO_SERVER_SECRET_KEY
            valueFrom:
              secretKeyRef:
                # this is minio.fullname or fullnameOverride
                name: minio
                key: secret-key
          - name: MINIO_SERVER_HOST
            # this is minio.fullname or fullnameOverride
            value: minio
          - name: MINIO_SERVER_PORT_NUMBER
            value: "9000"
          - name: MINIO_ALIAS
            value: minio
        command:
          - /bin/sh
          - -c
          - |
            mc config host add ${MINIO_ALIAS} http://${MINIO_SERVER_HOST}:${MINIO_SERVER_PORT_NUMBER} ${MINIO_SERVER_ACCESS_KEY} ${MINIO_SERVER_SECRET_KEY}
      containers:
      - name: expose-assets-buckets
        image: bitnami/minio-client
        env:
          - name: MINIO_SERVER_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                # this is minio.fullname or fullnameOverride
                name: minio
                key: access-key
          - name: MINIO_SERVER_SECRET_KEY
            valueFrom:
              secretKeyRef:
                # this is minio.fullname or fullnameOverride
                name: minio
                key: secret-key
          - name: MINIO_SERVER_HOST
            # this is minio.fullname or fullnameOverride
            value: minio
          - name: MINIO_SERVER_PORT_NUMBER
            value: "9000"
          - name: MINIO_ALIAS
            value: minio
        command:
          - /bin/sh
          - -c
          - |
            mc config host add ${MINIO_ALIAS} http://${MINIO_SERVER_HOST}:${MINIO_SERVER_PORT_NUMBER} ${MINIO_SERVER_ACCESS_KEY} ${MINIO_SERVER_SECRET_KEY}

            for bucket in food people shops ; do
              mc mb ${MINIO_ALIAS}/$bucket
              mc policy set public ${MINIO_ALIAS}/$bucket
            done
      restartPolicy: OnFailure