apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-assets-fixtures
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: initialize-assets-fixtures
        image: shopozor/assets-fixtures
        env:
          - name: MINIO_SERVER_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                # this is minio.fullname or fullnameOverride
                name: minio
                key: access-key
          - name: MINIO_SERVER_SECRET_KEY
            valueFrom:
              secretKeyRef:
                # this is minio.fullname or fullnameOverride
                name: minio
                key: secret-key
          - name: MINIO_SERVER_HOST
            # this is minio.fullname or fullnameOverride
            value: minio
          - name: MINIO_SERVER_PORT_NUMBER
            value: "9000"
          - name: MINIO_ALIAS
            value: minio
          - name: TIMEOUT
            value: "60"
        # TODO: the commands below need to be run only after the buckets have been exposed!
        command:
          - /bin/sh
          - -c
          - |
            echo "waiting $TIMEOUT seconds for ${MINIO_SERVER_PORT_NUMBER} to be ready on host ${MINIO_SERVER_HOST}"
            for i in `seq 1 $TIMEOUT`; do
              echo "waiting for minio service"
              mc config host add ${MINIO_ALIAS} http://${MINIO_SERVER_HOST}:${MINIO_SERVER_PORT_NUMBER} ${MINIO_SERVER_ACCESS_KEY} ${MINIO_SERVER_SECRET_KEY}
              [ "$?" -eq "0" ] && break || sleep 1
            done

            for category in `ls`; do
              for f in `ls $category/*` ; do
                mc cp $f ${MINIO_ALIAS}/$category/$(basename $f)
              done
            done
      restartPolicy: Never