apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-generate-site
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-generator-service
        image: busybox
        env:
        - name: SERVICE_NAME
          value: {{ include "chart.fullname" . }}
        command: ['sh', '-c', 'until nslookup $${SERVICE_NAME}; do echo "Waiting for $${SERVICE_NAME}"; sleep 2; done;']
      containers:
      - name: {{ .Chart.Name }}-generate-site
        image: curlimages/curl:latest
        env:
        - name: SERVICE_NAME
          value: {{ include "chart.fullname" . }}
        - name: SERVICE_PORT
          value: {{ .Values.service.port | quote }}
        command: ["curl", "http://$(SERVICE_NAME):$(SERVICE_PORT)/generate"]
      restartPolicy: OnFailure