apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-postgresql
  labels: {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  # TODO: we might want to generate this name randomly too and let keycloak, hasura, and postgresql deal with it
  postgresql-username: {{ .Values.postgresql.username | b64enc | quote }}
  repmgr-password: {{ randAlphaNum 10 | b64enc | quote }}